# ALL options listed at https://github.com/probe-rs/probe-rs/blob/master/probe-rs-tools/src/bin/probe-rs/cmd/cargo_embed/config/default.toml

[default.probe]
protocol = "Swd"
speed = 20000

## rust-dap
# usb_vid = "6666"
# usb_pid = "4444"
# serial = "test"

[default.flashing]
enabled = true

[default.reset]
enabled = true
halt_afterwards = false

[default.general]
chip = "RP2040"
log_level = "WARN"
# RP2040 does not support connect_under_reset
connect_under_reset = false

[default.rtt]
## Whether or not an RTTUI should be opened after flashing.
enabled = true
# The duration in ms for which the logger should retry to attach to RTT.
timeout = 3000
# Whether to save rtt history buffer on exit.
log_enabled = false
# Where to save rtt history buffer relative to manifest path.
log_path = "./logs"

up_channels = [
    { channel = 0, mode = "NoBlockSkip", format = "Defmt", show_timestamps = true, show_location = true}
]

down_channels = [ ]

tabs = [
    {up_channel = 0, name = "Defmt"}
]

[default.gdb]
enabled = false
gdb_connection_string = "127.0.0.1:2345"
